<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\pimto\Documents\Code\connections-lab-low-res-gallery\static\models\Test-v2.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import {
		T,
		type Props,
		type Events,
		type Slots,
		forwardEventHandlers,
		useThrelte
	} from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { AutoColliders, RigidBody } from '@threlte/rapier';
	import Sensor from '$lib/Sensor.svelte';
	import type { ProjectInfo } from '$lib/types';

	type $$Props = Props<THREE.Group> & { project: ProjectInfo | null };
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();
	export let project: ProjectInfo | null = null;

	type GLTFResult = {
		nodes: {
			Box003: THREE.Mesh;
			Box: THREE.Mesh;
			Box004: THREE.Mesh;
			Box002: THREE.Mesh;
		};
		materials: {
			M_08___Default: THREE.MeshStandardMaterial;
			M_02___Default: THREE.MeshStandardMaterial;
			M_07___Default: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/Test-v2.glb');
	gltf.then((gltf) => {
		console.log(gltf);
		// gltf.scene.traverse((o: THREE.Object3D<THREE.Object3DEventMap>) => {
		// 	// Add the Exit and Entry objects to the scene
		// 	if (o.name === 'Exit') {
		// 		ref.add(o);
		// 	}
		// 	if (o.name === 'Entry') {
		// 		ref.add(o);
		// 	}
		// });
		ref.add(gltf.scene);
	});

	const { size } = useThrelte();
	$: zoom = $size.width / 1600;

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[0.13, 0, 0.11]} rotation={[-Math.PI, 1.54, -Math.PI]}>
      <RigidBody>
			<AutoColliders shape={"trimesh"}>
        <T.Group position={[2.89, 0, 0.1]} rotation={[-Math.PI / 2, 0, 0]}>
          <T.Mesh
            receiveShadow
            castShadow
            geometry={gltf.nodes.Box003.geometry}
            material={gltf.materials.M_08___Default}
            scale={0}
          />
        </T.Group>
        <T.Group position={[-0.03, 0, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
          <RigidBody>
            <AutoColliders shape={'trimesh'}>
              <T.Mesh
                geometry={gltf.nodes.Box.geometry}
                material={gltf.materials.M_02___Default}
                scale={0}
              />
            </AutoColliders>
          </RigidBody>
        </T.Group>
        <T.Group position={[0.29, 0.83, -2.48]} rotation={[-Math.PI / 2, 0, 0]}>
          <T.Mesh
            geometry={gltf.nodes.Box004.geometry}
            material={gltf.materials.M_07___Default}
            scale={0}
          />
        </T.Group>
        <T.Group position={[-0.03, 0, -2.9]} rotation={[-Math.PI / 2, 0, 0]}>
          <T.Mesh
            geometry={gltf.nodes.Box002.geometry}
            material={gltf.materials.M_08___Default}
            scale={0}
          />
        </T.Group>
      </AutoColliders>
    </RigidBody>
		</T.Group>
		<T.PerspectiveCamera
			makeDefault={true}
			near={0.1}
			fov={31.74}
			position={[11.9, 4.94, 10.4]}
			rotation={[-0.38, 0.81, 0.31]}
		/>
		<T.PointLight
			intensity={0.32}
			decay={2}
			position={[1.03, 2.98, -1.94]}
			rotation={[-Math.PI, 1.54, -Math.PI]}
		/>
		<T.SpotLight
			intensity={100.74}
			angle={0.41}
			penumbra={1}
			decay={2}
			color="#ffe2ab"
			position={[10.92, 3.91, -0.18]}
			rotation={[-1.66, 1.28, 1.66]}
		/>

		<!-- <Sensor position={gltf.nodes.Entry.position} scale={gltf.nodes.Entry.scale} data={project} /> -->

		<!-- <RigidBody>
      <AutoColliders shape={"cuboid"}>
        <T.Mesh receiveShadow castShadow  geometry={gltf.nodes.Cube001.geometry}
        material={gltf.nodes.Entry.material}/>
      </AutoColliders>
    </RigidBody> -->
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
