<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\pimto\Documents\Code\connections-lab-low-res-gallery\static\models\TestSceneWithCamera.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { AutoColliders, Collider, RigidBody } from '@threlte/rapier';
	import { info, viewing } from '$lib';
	import type { ProjectInfo } from '$lib/types';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Box001: THREE.Mesh;
			Box002: THREE.Mesh;
			Box003: THREE.Mesh;
			Box004: THREE.Mesh;
		};
		materials: {
			M_02___Default: THREE.MeshStandardMaterial;
			M_08___Default: THREE.MeshStandardMaterial;
			M_07___Default: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/models/TestSceneWithCamera.gltf');
	// console.log(typeof gltf);

	gltf.then((gltf) => {
	  ref.add(gltf.scene)
	})

	console.log();

	const component = forwardEventHandlers();

	// let sensed = false;

	// $: present(sensed);

	// const present = (state: boolean) => {
	// 	info.set(state ? data : null);
	// 	viewing.set(state);
	// };

	export const project: ProjectInfo | null = null;
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
		{console.log('loading')}
	{:then gltf}
		{console.log('loaded', gltf)}
		<T.Group position={[0, 0, 0]}>
			<RigidBody>
				<AutoColliders shape={'cuboid'}>
					<!-- <T.PointLight intensity={0.32} decay={2} position={[2.02, 2.98, 0.95]} />
					<T.SpotLight
						intensity={1.74}
						angle={0.41}
						penumbra={1}
						decay={2}
						distance={19.74}
						color="#ffe2ab"
						position={[-5.27, 5.33, 10.66]}
					/> -->
					<T.PerspectiveCamera
						makeDefault={true}
						fov={31.74}
						position={[-10.6, 4.94, 11.5]}
						rotation={[-Math.PI / 9, -0.72, -0.21]}
					/>
					<T.Group position={[-0.03, 0, 0.02]} rotation={[-Math.PI / 2, 0, 0]}>
						<T.Mesh
							geometry={gltf.nodes.Box001.geometry}
							material={gltf.materials.M_02___Default}
							scale={0}
						/>
					</T.Group>
					<T.Group position={[-0.03, 0, -2.9]} rotation={[-Math.PI / 2, 0, 0]}>
						<T.Mesh
							geometry={gltf.nodes.Box002.geometry}
							material={gltf.materials.M_08___Default}
							scale={0}
						/>
					</T.Group>
					<T.Group position={[2.89, 0, 0.1]} rotation={[-Math.PI / 2, 0, 0]}>
						<T.Mesh
							geometry={gltf.nodes.Box003.geometry}
							material={gltf.materials.M_08___Default}
							scale={0}
						/>
					</T.Group>
					<T.Group position={[0.29, 0.83, -2.48]} rotation={[-Math.PI / 2, 0, 0]}>
						<T.Mesh
							geometry={gltf.nodes.Box004.geometry}
							material={gltf.materials.M_07___Default}
							scale={0}
						/>
					</T.Group>
				</AutoColliders>
			</RigidBody>
		</T.Group>
	{:catch error}
		{console.log(error)}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
