<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 C:\Users\pimto\Documents\Code\connections-lab-low-res-gallery\static\models\Test.gltf --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Plane: THREE.Mesh
      Cube003: THREE.Mesh
      Cube001: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/models/Test.gltf') //.then((result) => console.log(result))

  // Attach rapier collision groups to the objects starting with Zone

    

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Cube003.geometry}
      material={gltf.nodes.Cube003.material}
      position={[-5.85, 0.92, 4.93]}
      rotation={[-Math.PI, 0.86, -Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.nodes.Cube001.material}
      position={[-5.95, 0.89, -6.85]}
      rotation={[0, 0.89, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
